Repository debate-timer/debate-timer-fe, pull requests merged in 2024-12, with the labels that each got.

#2 docs: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#4 [DOCS] ISSUE 템플릿과 자동 할당 구현
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/docs-template.md
  .github/ISSUE_TEMPLATE/feat-template.md
  .github/ISSUE_TEMPLATE/fix-template.md
  .github/ISSUE_TEMPLATE/hotfix-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/ui-template.md
  .github/workflows/Auto_Issue_Setting.yml
Labels: docs

#6 [DOCS] PR 자동할당 yml 작성
  .github/workflows/Auto_PR_Setting.yml
Labels: docs

#8 [DOCS] Discord comment 알림 yml 작성
  .github/workflows/PR_Comment_Noti.yml
Labels: docs

#10 [CHORE] 프로젝트 초기 세팅
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  setup.ts
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  stylelint.config.cjs
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: chore

#13 [CHORE] prettier 설정 추가
  .prettierrc
Labels: chore

#14 [FEAT] 타임 테이블 구성 화면 레이아웃, 찬성, 반대, 작전 시간, 타이머 추가 버튼 컴포넌트 구현
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  src/App.tsx
  src/index.css
  src/layout/components/footer/FixedFooterWrapper.tsx
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/layout/components/main/ContentContanier.tsx
  src/layout/defaultLayout/DefaultLayout.tsx
  src/page/TableSetupPage/TableSetup.tsx
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.stories.tsx
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
  src/page/TableSetupPage/components/ProsAndConsTitle/ PropsAndConsTitle.stories.tsx
  src/page/TableSetupPage/components/ProsAndConsTitle/PropsAndConsTitle.tsx
  src/page/TableSetupPage/components/TimerCreationButton/TimerCreationButton.stories.tsx
  src/page/TableSetupPage/components/TimerCreationButton/TimerCreationButton.tsx
  src/type/type.ts
  src/util/formatting.ts
  tailwind.config.js
Labels: feat

#22 [FEAT] 페이지 라우팅 적용
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/page/LoginPage/LoginPage.tsx
  src/route.tsx
  tsconfig.app.json
Labels: feat

#17 [FEAT] 타이머 박스 생성 모달 구현
  package-lock.json
  package.json
  src/App.test.tsx
  src/hooks/useModal.test.tsx
  src/hooks/useModal.tsx
  src/page/TableSetupPage/TableSetup.stories.tsx
  src/page/TableSetupPage/TableSetup.test.tsx
  src/page/TableSetupPage/TableSetup.tsx
  src/page/TableSetupPage/components/TimerCreationContent/TimerCreationContent.tsx
  src/type/type.ts
  src/util/GlobalPortal/PortalConsumer.tsx
  src/util/GlobalPortal/PortalContext.ts
  src/util/GlobalPortal/PortalProvider.tsx
  src/util/GlobalPortal/index.ts
Labels: feat

#27 lint와 test를 넣은 CI yml 파일 작성
  .github/workflows/CI.yml
Labels: chore

#26 [FEAT] 테이블 목록화면 구현
  src/hooks/useModal.tsx
  src/main.tsx
  src/page/LoginPage/LoginPage.tsx
  src/page/LoginPage/components/LinkButton/LinkButton.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/AddTable.tsx
  src/page/TableListPage/components/Modal/CreateTableButton.tsx
  src/page/TableListPage/components/Modal/CreateTableModal.tsx
  src/page/TableListPage/components/Modal/DropdownForDebateType.tsx
  src/page/TableListPage/components/Table.tsx
  src/page/TableSetupPage/components/TimerCreationContent/TimerCreationContent.tsx
  src/type/type.ts
Labels: feat

#31 [TEST] 로그인 페이지 Storybook 테스트코드 구현
  src/page/LoginPage/LoginPage.stories.tsx
  src/page/LoginPage/components/LinkButton/LinkButton.stories.tsx
Labels: feat, test

#29 [FIX] 타임 테이블 구성 페이지 피드백 사항 반영
  src/layout/components/footer/FixedFooterWrapper.tsx
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/layout/components/main/ContentContanier.tsx
  src/page/TableSetupPage/TableSetup.tsx
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
  src/page/TableSetupPage/components/TimerCreationContent/TimerCreationContent.tsx
  src/type/type.ts
  src/util/formatting.ts
Labels: fix

#35 [TEST] 테이블 목록 컴포넌트 Storybook 테스트코드 구현
  package-lock.json
  package.json
  src/page/TableListPage/TableListPage.stories.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/Modal/DropdownForDebateType.stories.tsx
  src/page/TableListPage/components/Table/AddTable.tsx
  src/page/TableListPage/components/Table/Table.stories.tsx
  src/page/TableListPage/components/Table/Table.tsx
  src/page/TableSetupPage/components/TimerCreationContent/TimerCreationContent.tsx
Labels: feat, test

#37 [TEST] 로그인 및 테이블 조회 컴포넌트 테스트코드 구현
  src/page/LoginPage/LoginPage.test.tsx
  src/page/TableListPage/TableListPage.test.tsx
Labels: feat, test
