Repository debate-timer/debate-timer-fe, pull requests merged in 2025-02, with the labels that each got.

#104 [Refactor] 1차 UT에서 발생한 피드백 반영
  src/apis/apis.ts
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/components/Modal/CreateTableModal.tsx
  src/page/TableListPage/components/Modal/EditTableModal.tsx
  src/page/TableListPage/components/Table/Table.tsx
Labels: refactor

#109 [FIX] `useTimer` 훅 매개변수 오류 수정
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
Labels: fix

#105 [FEAT] 기존 닉네임 기반 로그인을 구글 로그인으로 변경
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-storybook.yml
  .storybook/preview.tsx
  package.json
  src/apis/apis.ts
  src/apis/axiosInstance.ts
  src/apis/primitives.ts
  src/apis/responseTypes.ts
  src/components/GoogleButton.tsx
  src/hooks/mutations/useAddTable.ts
  src/hooks/mutations/useDeleteParliamentaryDebateTable.ts
  src/hooks/mutations/useLogout.ts
  src/hooks/mutations/usePostUser.ts
  src/hooks/mutations/usePutParliamentaryDebateTable.ts
  src/hooks/query/useGetDebateTableList.ts
  src/hooks/query/useGetParliamentaryTableData.ts
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/LoginPage/LoginPage.test.tsx
  src/page/LoginPage/LoginPage.tsx
  src/page/LoginPage/OAuth.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/TableListPage.test.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TimerPage/TimerPage.stories.tsx
  src/page/TimerPage/TimerPage.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/routes.tsx
  src/util/accessToken.ts
  src/util/memberIdToken.ts
Labels: feat, refactor

#115 [FIX] access token 만료 시, refresh 토큰으로 access toekn이 최신화 되지않는 오류 수정
  src/apis/axiosInstance.ts
Labels: fix

#119 deploy: 임시 PR
  src/apis/axiosInstance.ts
Labels: deploy

#118 [FEAT] Debate Timer 서비스에 Google Analytics 적용
  package-lock.json
  package.json
  src/main.tsx
  src/routes/routes.tsx
  src/util/setupGoogleAnalytics.tsx
Labels: feat

#124 [FEAT] 타이머 개선 외
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package-lock.json
  src/apis/primitives.ts
  src/components/GoogleButton.tsx
  src/page/LoginPage/LoginPage.test.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx
  src/page/TimerPage/components/Timer/TimeTableItem.tsx
  src/page/TimerPage/components/Timer/TimerComponent.tsx
  src/page/TimerPage/components/Timer/TimerController.tsx
  src/page/TimerPage/components/Timer/TimerTimeTable.tsx
  src/page/TimerPage/components/common/FirstUseToolTip.tsx
  src/page/TimerPage/components/common/HeaderButtons.tsx
  src/page/TimerPage/components/common/TimerDisplay.tsx
  src/page/TimerPage/components/common/TimerTextButton.tsx
  src/util/validateUserAgent.ts
  tailwind.config.js
Labels: feat, chore, fix

#123 [FEAT] 토론 테이블 생성, 수정 개선
  src/apis/apis.ts
  src/apis/responseTypes.ts
  src/constants/languageMapping.ts
  src/hooks/mutations/useAddTable.ts
  src/hooks/mutations/usePutParliamentaryDebateTable.ts
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/DebatePanel/DebatePanel.tsx
  src/page/TableComposition/components/DropdownForDebateType/DropdownForDebateType.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.stories.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableOverviewPage/TableOverview.stories.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummary.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummaryItem.tsx
  src/page/TimerPage/components/DebateInfoSummary.tsx
  src/page/TimerPage/components/Timer/TimeTableItem.tsx
  src/page/TimerPage/components/Timer/TimerComponent.tsx
  src/page/TimerPage/components/Timer/TimerTimeTable.tsx
  src/type/type.ts
Labels: feat

#129 [CHORE] 컬러 시스템 작성
  index.html
  public/debate_logo.jpg
  tailwind.config.js
Labels: chore

#135 [FIX] Storybook 배포 오류 수정
  .github/workflows/deploy-storybook.yml
Labels: fix

#132 [REFACTOR] 헤더 UI를 공통화
  src/components/HeaderTableInfo/HeaderTableInfo.tsx
  src/components/HeaderTitle/HeaderTitle.tsx
  src/components/IconButton/IconButton.tsx
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableOverviewPage/TableOverview.tsx
Labels: feat, refactor

#137 [CHORE] PROD 배포에 CI 추가
  .github/ISSUE_TEMPLATE/deploy-template.md
  .github/workflows/CI.yml
Labels: chore

#139 [FEAT] ContentContanier의 padding유무를 props로 전달
  src/layout/components/main/ContentContanier.tsx
Labels: feat

#140 [REFACTOR] 타이머에 새로운 색상 테이블과 헤더 반영
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/AdditionalTimerControlButton.tsx
  src/page/TimerPage/components/AdditionalTimerController.tsx
  src/page/TimerPage/components/FirstUseToolTip.tsx
  src/page/TimerPage/components/HeaderButtons.tsx
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/TimeTableItem.tsx
  src/page/TimerPage/components/Timer.tsx
  src/page/TimerPage/components/TimerController.tsx
  src/type/type.ts
Labels: refactor, chore, fix

#143 [DEPLOY] 배포 진행
  .github/ISSUE_TEMPLATE/deploy-template.md
  .github/workflows/CI.yml
  .github/workflows/deploy-storybook.yml
  index.html
  public/debate_logo.jpg
  public/sounds/bell-finish.mp3
  public/sounds/bell-warning.mp3
  src/components/HeaderTableInfo/HeaderTableInfo.tsx
  src/components/HeaderTitle/HeaderTitle.tsx
  src/components/IconButton/IconButton.tsx
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/layout/components/main/ContentContanier.tsx
  src/mocks/handlers.ts
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableOverviewPage/TableOverview.stories.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TimerPage/TimerLoadingPage.tsx
  src/page/TimerPage/TimerPage.stories.tsx
  src/page/TimerPage/TimerPage.test.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummary.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummaryItem.tsx
  src/page/TimerPage/components/AdditionalTimerControlButton.tsx
  src/page/TimerPage/components/AdditionalTimerController.tsx
  src/page/TimerPage/components/DebateInfoSummary.tsx
  src/page/TimerPage/components/FirstUseToolTip.tsx
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/TimeTableItem.tsx
  src/page/TimerPage/components/Timer.tsx
  src/page/TimerPage/components/Timer/TimeTableItem.tsx
  src/page/TimerPage/components/Timer/TimerComponent.tsx
  src/page/TimerPage/components/Timer/TimerController.tsx
  src/page/TimerPage/components/Timer/TimerTimeTable.tsx
  src/page/TimerPage/components/TimerController.tsx
  src/page/TimerPage/components/common/FirstUseToolTip.tsx
  src/page/TimerPage/components/common/HeaderButtons.tsx
  src/page/TimerPage/components/common/TimerDisplay.tsx
  src/page/TimerPage/components/common/TimerIconButton.tsx
  src/page/TimerPage/components/common/TimerTextButton.tsx
  src/page/TimerPage/stories/AdditionalTimerControlButton.stories.tsx
  src/page/TimerPage/stories/AdditionalTimerController.stories.tsx
  src/page/TimerPage/stories/FirstUseToolTip.stories.tsx
  src/page/TimerPage/stories/TimeTable.stories.tsx
  src/page/TimerPage/stories/TimeTableItem.stories.tsx
  src/page/TimerPage/stories/Timer.stories.tsx
  src/page/TimerPage/stories/TimerController.stories.tsx
  src/type/type.ts
  tailwind.config.js
Labels: deploy
