Repository debate-timer/debate-timer-fe, pull requests merged in 2025-01, with the labels that each got.

#39 [CHORE] API 처리를 위해 패키지 추가
  .env.dev-mock
  .env.development
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.tsx
  src/mocks/handlers.tsx
  src/vite-env.d.ts
Labels: chore, config

#44 [FEAT] 테이블 수정 및 삭제 구현
  package-lock.json
  package.json
  src/hooks/useModal.tsx
  src/page/TableListPage/TableListPage.test.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
  src/page/TableListPage/components/Modal/EditModalButton.tsx
  src/page/TableListPage/components/Modal/EditTableButton.tsx
  src/page/TableListPage/components/Modal/EditTableModal.tsx
  src/page/TableListPage/components/Table/Table.tsx
Labels: feat, refactor

#47 [FEAT] 타임박스의 수정을 드래그앤드롭으로 변경하는 기능 구현
  src/hooks/useDragAndDrop.tsx
  src/hooks/useThrottle.ts
  src/page/TableSetupPage/TableSetup.tsx
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
  src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.stories.tsx
  src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.tsx
Labels: feat

#50 [CHORE] storybook에 전역적인 decorators 설정 추가
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/page/LoginPage/LoginPage.stories.tsx
  src/page/LoginPage/components/LinkButton/LinkButton.stories.tsx
  src/page/TableListPage/TableListPage.stories.tsx
  src/page/TableListPage/components/Modal/DropdownForDebateType.stories.tsx
  src/page/TableListPage/components/Table/Table.stories.tsx
  src/page/TableOverviewPage/TableOverview.stories.tsx
  src/page/TableSetupPage/TableSetup.stories.tsx
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
  src/page/TableSetupPage/components/EditDeleteButtons/EditDeleteButtons.stories.tsx
Labels: chore

#54 [FIX] Mock Handler 파일에서 타입 에러 해결
  src/mocks/handlers.tsx
Labels: fix

#62 [CHORE] VS Code 작업 영역에 대한 설정 파일 추가
  .vscode/settings.json
Labels: chore

#58 [FEAT] 타이머 화면 구현
  .storybook/main.ts
  .storybook/preview.tsx
  public/sounds/ding-once-edit.mp3
  public/sounds/ding-twice-edit.mp3
  public/spinner.gif
  src/index.css
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/page/TableSetupPage/components/DebatePanel/DebatePanel.tsx
  src/page/TimerPage/TimerPage.stories.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/DebateInfoSummary.tsx
  src/page/TimerPage/components/Timer/Timer.tsx
  src/page/TimerPage/components/Timer/TimerController.tsx
  src/page/TimerPage/components/TimerComponent.tsx
  src/page/TimerPage/components/common/TimerIconButton.tsx
  src/page/TimerPage/components/common/TimerTextButton.tsx
  src/route.tsx
  src/type/type.ts
  src/util/formatting.ts
  tailwind.config.js
Labels: feat, refactor, fix

#65 [FEAT] `ErrorBoundary` 도입
  src/apis/responseTypes.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
  src/index.css
  src/main.tsx
  src/page/TimerPage/TimerPage.tsx
  src/route.tsx
Labels: feat

#57 [FEAT] API 연결과 테이블 생성과 수정을 위해 funnel 패턴을 이용하여 멀티 스텝 폼 구현
  .storybook/preview.tsx
  setup.ts
  src/apis/responseTypes.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
  src/constants/languageMapping.ts
  src/hooks/mutations/useAddTable.ts
  src/hooks/mutations/useDeleteParliamentaryDebateTable.ts
  src/hooks/mutations/usePostUser.ts
  src/hooks/mutations/usePutParliamentaryDebateTable.ts
  src/hooks/query/useGetDebateTableList.ts
  src/hooks/query/useGetParliamentaryTableData.ts
  src/hooks/useBrowserStorage.tsx
  src/hooks/useDragAndDrop.tsx
  src/hooks/useFunnel.tsx
  src/index.css
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/page/LoginPage/LoginPage.test.tsx
  src/page/LoginPage/LoginPage.tsx
  src/page/TableComposition/TableComposition.stories.tsx
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/DebatePanel/DebatePanel.stories.tsx
  src/page/TableComposition/components/DebatePanel/DebatePanel.tsx
  src/page/TableComposition/components/DeleteConfirmContent/DeleteConfirmContent.tsx
  src/page/TableComposition/components/DropdownForDebateType/DropdownForDebateType.stories.tsx
  src/page/TableComposition/components/DropdownForDebateType/DropdownForDebateType.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.stories.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/components/TimerCreationButton/TimerCreationButton.stories.tsx
  src/page/TableComposition/components/TimerCreationButton/TimerCreationButton.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/TableListPage.test.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
  src/page/TableListPage/components/Modal/EditButton.tsx
  src/page/TableListPage/components/Modal/EditModalButton.tsx
  src/page/TableListPage/components/Table/AddTable.tsx
  src/page/TableListPage/components/Table/Table.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TableSetupPage/TableSetup.stories.tsx
  src/page/TableSetupPage/TableSetup.test.tsx
  src/page/TimerPage/TimerPage.tsx
  src/route.tsx
  src/type/type.ts
Labels: feat

#69 [HOTFIX] 에러바운더리 코드가 삭제된 것에 대한 반영
  src/apis/responseTypes.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
  src/index.css
  src/main.tsx
  src/page/TimerPage/TimerPage.tsx
Labels: hotfix

#66 [REFACTOR] 타이머 기능 개선 외
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorBoundaryWrapper.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
  src/page/TimerPage/TimerLoadingPage.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/DebateInfoSummary.tsx
  src/page/TimerPage/components/Timer/Timer.tsx
  src/page/TimerPage/components/Timer/TimerController.tsx
  src/page/TimerPage/components/TimerComponent.tsx
Labels: refactor, fix

#73 [HOTFIX] GitHub Actions 빌드 실패 문제 해결
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/components/Table/Table.stories.tsx
Labels: hotfix

#71 [FEAT] 닉네임 기반 로그인 구현
  src/apis/responseTypes.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/page/LoginPage/LoginPage.test.tsx
  src/page/LoginPage/LoginPage.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/route.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/routes.tsx
  src/util/memberIdToken.ts
Labels: feat, refactor

#77 [FEAT] 추가 작전 시간 타이머 구현 외
  .env.dev-mock
  .env.development
  .gitignore
  src/apis/endpoints.ts
  src/apis/primitives.ts
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/hooks/useModal.tsx
  src/main.tsx
  src/page/TableComposition/components/DeleteConfirmContent/DeleteConfirmContent.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummary.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerSummaryItem.tsx
  src/page/TimerPage/components/Timer/TimerComponent.tsx
  src/page/TimerPage/components/Timer/TimerController.tsx
  src/page/TimerPage/components/common/TimerDisplay.tsx
  src/page/TimerPage/components/common/TimerTextButton.tsx
  vite.config.ts
Labels: feat

#82 [CHORE] 배포 최적화 및 배포 환경 구분
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  index.html
  package-lock.json
  package.json
  public/mockServiceWorker.js
Labels: chore, fix

#84 [HOTFIX] 배포된 앱이 서버와 통신하지 못하는 문제 수정
  src/apis/primitives.ts
Labels: hotfix

#86 [FIX] PostUserResponseType타입 수정, TableOverview에서 tableId를 url에서 정상적으로 가져오도록 수정
  src/apis/responseTypes.ts
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableOverviewPage/TableOverview.tsx
Labels: fix

#92 [FIX] QA에서 식별한 버그 해결 - 숀
  package-lock.json
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableListPage/TableListPage.test.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerComponent.tsx
  src/page/TimerPage/components/AdditionalTimer/AdditionalTimerController.tsx
  src/page/TimerPage/components/common/TimerDisplay.tsx
Labels: feat, fix

#93 [FIX] QA에서 식별한 버그 해결 - 치코
  package.json
  src/hooks/useFunnel.tsx
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
Labels: fix

#94 [FIX] QA에서 식별한 버그 해결 - 엘
  src/hooks/mutations/useDeleteParliamentaryDebateTable.ts
  src/page/LoginPage/LoginPage.test.tsx
  src/page/LoginPage/LoginPage.tsx
  src/page/TableListPage/components/Table/Table.tsx
Labels: fix

#81 [FIX, CHORE] mock에서 드래그앤 드롭 UI가 깨지는 문제 수정, Storybook 자동 배포 yml 작성
  .github/workflows/deploy-storybook.yml
  package.json
  src/mocks/handlers.ts
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
Labels: fix

#99 [FEAT] invalidateQueries 사용하여 Table 삭제 시 즉시 업데이트 반영
  src/hooks/mutations/useDeleteParliamentaryDebateTable.ts
Labels: feat

#102 [REFACTOR] 1차 UT에 있었던 1, 2순위 수정 사항 반영
  src/hooks/useDragAndDrop.tsx
  src/layout/components/main/ContentContanier.tsx
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/DebatePanel/DebatePanel.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
Labels: refactor
