Repository debate-timer/debate-timer-fe, pull requests merged in 2025-08, with the labels that each got.

#326 [FEAT] 커스텀 타종 설정 추가
  src/apis/apis/debateTable.ts
  src/components/ShareModal/ShareModal.stories.tsx
  src/constants/sample_table.ts
  src/mocks/handlers/customize.ts
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBox/TimeBox.stories.tsx
  src/page/TableComposition/components/TimeBoxManageButtons/TimeBoxManageButtons.stories.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/hooks/useBellSound.ts
  src/page/TimerPage/hooks/useTimerPageState.ts
  src/page/TimerPage/stories/NormalTimer.stories.tsx
  src/page/TimerPage/stories/NormalTimerTestPage.stories.tsx
  src/type/type.ts
  src/util/arrayEncoding.test.ts
  src/util/formatting.ts
Labels: feat

#330 [FIX] 비회원으로 로그인 하지 않고 뒤로 가기를 눌렀을 때 에러 발생 문제 해결
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/OAuthPage/OAuth.tsx
  src/page/TimerPage/components/LoginAndStoreModal.tsx
Labels: fix

#339 [FEAT] 코인 토스 기능 구현
  public/sounds/cointoss-result.mp3
  public/sounds/cointoss.mp3
  src/assets/teamSelection/coinback.png
  src/assets/teamSelection/coinfront.png
  src/assets/teamSelection/coins.png
  src/assets/teamSelection/cointoss.png
  src/page/TableOverviewPage/TableOverviewPage.tsx
  src/page/TableOverviewPage/components/TeamSelectionModal/TeamSelectionModal.tsx
Labels: feat

#344 [REFACTOR] 타종 소리를 횟수에 따른 3개의 정적 파일로 변경
  public/sounds/bell-1.mp3
  public/sounds/bell-2.mp3
  public/sounds/bell-3.mp3
  public/sounds/bell-finish.mp3
  public/sounds/bell-warning.mp3
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TimerPage/hooks/useBellSound.ts
Labels: refactor

#346 [DOCS] README.md 파일에 프로젝트 설명 추가
  README.md
Labels: docs

#351 [DESIGN] 사소한 디자인 개선 사항 적용
  src/assets/timer/normal_timer_cons.jpg
  src/assets/timer/normal_timer_cons.png
  src/assets/timer/normal_timer_neutral.jpg
  src/assets/timer/normal_timer_neutral.png
  src/assets/timer/normal_timer_pros.jpg
  src/assets/timer/normal_timer_pros.png
  src/assets/timer/time_based_timer.jpg
  src/assets/timer/time_based_timer.png
  src/assets/timer/time_based_timer_only_total.jpg
  src/components/ProsAndConsTitle/PropsAndConsTitle.tsx
  src/components/icons/LeftArrow.tsx
  src/components/icons/RightArrow.tsx
  src/index.css
  src/page/TableComposition/components/TimeBox/TimeBox.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/NormalTimer.tsx
  src/page/TimerPage/components/RoundControlRow.tsx
Labels: design

#350 [FIX] 타이머 오류 해결
  src/page/TimerPage/components/NormalTimer.tsx
  src/page/TimerPage/components/TimeBasedTimer.tsx
Labels: fix
