Repository debate-timer/debate-timer-fe, pull requests merged in 2025-06, with the labels that each got.

#283 [FEAT] 랜딩페이지 구현
  src/assets/landing/preview.webm
  src/assets/landing/review-icon.svg
  src/assets/landing/section1-1.png
  src/assets/landing/section1-2.png
  src/assets/landing/section2-1.png
  src/assets/landing/section2-2.png
  src/assets/landing/section2-3.png
  src/assets/landing/section3-1.png
  src/assets/landing/section3-2.png
  src/assets/landing/section5-1.png
  src/constants/reviews.ts
  src/constants/urls.ts
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/LandingPage/LandingPage.stories.tsx
  src/page/LandingPage/LandingPage.tsx
  src/page/LandingPage/components/Header.tsx
  src/page/LandingPage/components/MainSection.tsx
  src/page/LandingPage/components/ReportSection.tsx
  src/page/LandingPage/components/ReviewCard.tsx
  src/page/LandingPage/components/ReviewSection.tsx
  src/page/LandingPage/components/TableSection.tsx
  src/page/LandingPage/components/TimeTableSection.tsx
  src/page/LandingPage/components/TimerSection.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/routes.tsx
  tailwind.config.js
Labels: feat, design

#286 [FIX] URL 공유 기능 및 비회원 플로우 버그 수정
  src/apis/axiosInstance.ts
  src/constants/sample_table.ts
  src/constants/urls.ts
  src/page/LandingPage/LandingPage.tsx
  src/page/TableSharingPage/TableSharingPage.tsx
Labels: fix

#289 [HOTFIX] 배포 워크플로가 환경 변수를 읽지 못하는 오류 수정
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: fix, hotfix
