Repository debate-timer/debate-timer-fe, pull requests merged in 2025-07, with the labels that each got.

#299 [CHORE] 팀 구성원 변경에 따른 Auto PR 스크립트 수정
  .github/workflows/Auto_PR_Setting.yml
Labels: chore

#303 [CHORE] GitHub 저장소 이슈 목록을 Notion으로 동기화
  .github/workflows/Notion_Sync.yml
  notion_sync.py
Labels: chore

#300 [DESIGN] 로그인/로그아웃 버튼 디자인 변경
  src/apis/axiosInstance.ts
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/LandingPage/LandingPage.tsx
  src/page/LandingPage/components/Header.tsx
  src/page/LandingPage/components/MainSection.tsx
  src/page/LandingPage/hooks/useLandingPageHandlers.ts
Labels: feat, chore, design

#306 [Win-CHORE] Electron 사용 설정
  .gitignore
  electron/main.ts
  electron/preload.ts
  package-lock.json
  package.json
  public/icon.ico
  tailwind.config.js
  vite.config.ts
Labels: chore

#304 [REFACTOR] TimerPage 비즈니스 로직 분리
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/FirstUseToolTipModal.tsx
  src/page/TimerPage/components/LoginAndStoreModal.tsx
  src/page/TimerPage/components/NormalTimer.tsx
  src/page/TimerPage/components/NormalTimerTestPage.tsx
  src/page/TimerPage/components/RoundControlRow.tsx
  src/page/TimerPage/components/TimeBasedTimer.tsx
  src/page/TimerPage/components/TimerController.tsx
  src/page/TimerPage/components/TimerView.tsx
  src/page/TimerPage/hooks/useBellSound.ts
  src/page/TimerPage/hooks/useNormalTimer.ts
  src/page/TimerPage/hooks/useTimeBasedTimer.ts
  src/page/TimerPage/hooks/useTimerBackground.ts
  src/page/TimerPage/hooks/useTimerHotkey.ts
  src/page/TimerPage/hooks/useTimerPageModal.ts
  src/page/TimerPage/hooks/useTimerPageState.ts
  src/page/TimerPage/stories/NormalTimer.stories.tsx
  src/page/TimerPage/stories/NormalTimerTestPage.stories.tsx
  src/page/TimerPage/stories/TimeBasedTimer.stories.tsx
  src/page/TimerPage/stories/TimerController.stories.tsx
  src/type/type.ts
Labels: refactor

#315 [FIX] 타이머 키보드 오류 수정
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/hooks/useTimerHotkey.ts
Labels: fix

#316 [FEAT] 타임박스 복사 기능 구현
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableComposition/components/TimeBox/TimeBox.stories.tsx
  src/page/TableComposition/components/TimeBox/TimeBox.tsx
  src/page/TableComposition/components/TimeBoxManageButtons/TimeBoxManageButtons.stories.tsx
  src/page/TableComposition/components/TimeBoxManageButtons/TimeBoxManageButtons.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableOverviewPage/TableOverview.tsx
Labels: feat

#321 [FIX] 버튼 "따닥"으로 인한 중복 호출로 시간표가 여러 개 생기는 문제 해결
  src/hooks/mutations/useAddDebateTable.ts
  src/hooks/mutations/usePreventDuplicateMutation.ts
  src/hooks/mutations/usePutDebateTable.ts
  src/main.tsx
  src/page/TableComposition/TableComposition.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
Labels: fix

#325 [DESIGN] 비동기 처리 관련 컴포넌트 개선
  src/components/ClearableInput/ClearableInput.stories.tsx
  src/components/ClearableInput/ClearableInput.tsx
  src/components/ErrorIndicator/ErrorIndicator.stories.tsx
  src/components/ErrorIndicator/ErrorIndicator.tsx
  src/components/HeaderTableInfo/HeaderTableInfo.tsx
  src/components/HeaderTitle/HeaderTitle.tsx
  src/components/LabeledCheckBox/LabeledCheckBox.stories.tsx
  src/components/LabeledCheckBox/LabeledCheckBox.tsx
  src/components/LoadingIndicator/LoadingIndicator.stories.tsx
  src/components/LoadingIndicator/LoadingIndicator.tsx
  src/components/Skeleton/Skeleton.stories.tsx
  src/components/Skeleton/Skeleton.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TimerPage/components/FirstUseToolTip.tsx
Labels: design
