Repository debate-timer/debate-timer-fe, pull requests merged in 2025-09, with the labels that each got.

#359 [DESIGN] 종소리 설정에 아코디언 UI 적용
  src/components/NotificationBadge/NotificationBadge.stories.tsx
  src/components/NotificationBadge/NotificationBadge.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  tailwind.config.js
Labels: design

#352 [FIX] 시간표 수정 화면과 레이아웃의 오류 해결
  src/layout/components/footer/StickyFooterWrapper.tsx
  src/layout/components/header/StickyTriSectionHeader.tsx
  src/page/TableComposition/components/TimeBox/TimeBox.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
Labels: fix

#356 [FEAT] 메인 페이지 디자인 변경 및 토론 템플릿 섹션 추가
  src/assets/landing/bell_setting.png
  src/assets/landing/bottom_arrow.png
  src/assets/landing/debate_info_setting.png
  src/assets/landing/key_info.png
  src/assets/landing/table_list.png
  src/assets/landing/timebox_add_button.png
  src/assets/landing/timebox_step.png
  src/assets/landing/timebox_step_button.png
  src/assets/landing/timeout_button.png
  src/assets/landing/timer.png
  src/assets/landing/timer_operation_time.png
  src/assets/landing/timer_timebased.png
  src/assets/landing/two_timer.png
  src/assets/template_logo/government.png
  src/assets/template_logo/han_alm.png
  src/assets/template_logo/hantomak.png
  src/assets/template_logo/igam.png
  src/assets/template_logo/jungseonto.png
  src/assets/template_logo/kogito.png
  src/assets/template_logo/kondae_time.png
  src/assets/template_logo/nogotte.png
  src/assets/template_logo/osansi.png
  src/assets/template_logo/seobangjeongto.png
  src/assets/template_logo/todallae.png
  src/assets/template_logo/visual.png
  src/constants/debate_template.ts
  src/constants/urls.ts
  src/page/LandingPage/LandingPage.tsx
  src/page/LandingPage/components/ReviewSection.tsx
  src/page/LandingPage/components/ScrollHint.tsx
  src/page/LandingPage/components/TableSection.tsx
  src/page/LandingPage/components/TemplateApplicationSection.tsx
  src/page/LandingPage/components/TemplateCard.tsx
  src/page/LandingPage/components/TemplateList.tsx
  src/page/LandingPage/components/TemplateSelection.tsx
  src/page/LandingPage/components/TimeTableSection.tsx
  src/page/LandingPage/components/TimerSection.tsx
  src/type/type.ts
Labels: feat

#363 [FEAT] 토론종료화면 구현
  src/assets/debateEnd/clap.png
  src/assets/debateEnd/feedback_timer.png
  src/assets/debateEnd/vote_stamp.png
  src/page/DebateEndPage/DebateEndPage.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/hooks/useTimerPageModal.ts
  src/routes/routes.tsx
Labels: feat

#364 [FIX] 코인토스 플로우 추가 및 버그 해결
  src/page/TableOverviewPage/TableOverviewPage.tsx
  src/page/TableOverviewPage/components/TeamSelectionModal/TeamSelectionModal.tsx
  src/type/type.ts
Labels: fix

#371 [HOTFIX] 토론 템플릿 URL 오류 수정
  src/constants/debate_template.ts
Labels: hotfix

#373 [FIX] 열린토론대회 토론 템플릿 데이터 변경
  src/constants/debate_template.ts
Labels: fix

#374 [DEPLOY] 배포
  src/constants/debate_template.ts
Labels: deploy
