Repository debate-timer/debate-timer-fe, pull requests merged in 2025-04, with the labels that each got.

#207 [FEAT] 자유토론 타이머 페이지 구현
  src/assets/img/keyboard_key_A.png
  src/assets/img/keyboard_key_l.png
  src/components/KeyIcon/KeyIcon.tsx
  src/mocks/handlers/customize.ts
  src/page/CustomizeTimerPage/CustomizeTimerPage.stories.tsx
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/components/AdditionalTimerControlButton.tsx
  src/page/CustomizeTimerPage/components/AdditionalTimerController.tsx
  src/page/CustomizeTimerPage/components/FirstUseToolTip.tsx
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
  src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx
  src/page/CustomizeTimerPage/components/TimerController.tsx
  src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
  src/page/CustomizeTimerPage/hooks/useNomalTimer.ts
  src/page/CustomizeTimerPage/stories/AdditionalTimerControlButton.stories.tsx
  src/page/CustomizeTimerPage/stories/AdditionalTimerController.stories.tsx
  src/page/CustomizeTimerPage/stories/FirstUseToolTip.stories.tsx
  src/page/CustomizeTimerPage/stories/TimeBasedTimer.stories.tsx
  src/page/CustomizeTimerPage/stories/TimerController.stories.tsx
  src/routes/routes.tsx
  src/type/type.ts
  tailwind.config.js
Labels: feat, design

#216 [FIX] 의회식 타이머 개선 사항 적용
  src/hooks/useModal.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/FirstUseToolTip.tsx
  src/page/TimerPage/components/Timer.tsx
  src/page/TimerPage/components/TimerController.tsx
  tailwind.config.js
Labels: fix

#221 [CHORE] 일부 개발 환경 개선 사항 적용
  .github/workflows/Issue_Noti.yml
  .github/workflows/PR_Comment_Noti.yml
  .storybook/preview-head.html
Labels: chore

#226 [FIX] 의회식 토론 타이머 토론 종료 시, overview url 이동 패턴 변경
  src/page/TimerPage/TimerPage.tsx
Labels: fix

#227 [FIX] Storybook 배포 진행되지 않는 문제 수정
  .github/workflows/deploy-storybook.yml
Labels: fix

#231 [FIX] 사전에 작전시간을 설정한 경우, 타이머 페이지에서 작전 시간 선택 버튼이 보이지 않도록 수정
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
Labels: fix

#229 [FIX] 자유토론 타이머 오류 해결
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/components/FirstUseToolTip.tsx
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
  src/page/CustomizeTimerPage/hooks/useNormalTimer.ts
  src/page/CustomizeTimerPage/stories/NormalTimer.stories.tsx
  src/page/CustomizeTimerPage/stories/TimeBasedTimer.stories.tsx
Labels: fix

#233 [FIX] 커스텀 토론 페이지 자유토론 타이머 2차 QA 수정
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
Labels: fix

#238 [FIX] NomalTimer의 헤더 문구가 설정된 문자열에 출력되지 않는 문제 수정
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
Labels: fix

#240 [FIX] 사용자 지정 토론 NormalTimer의 추가 작전 시간 발언자 정보 삭제
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
Labels: fix
