Repository debate-timer/debate-timer-fe, pull requests merged in 2025-05, with the labels that each got.

#244 [CHORE] 의회식 토론 생성 차단
  src/mocks/handlers/customize.ts
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
Labels: chore

#247 [DEPLOY] 배포 진행
  src/mocks/handlers/customize.ts
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
Labels: deploy

#246 [FEAT] 배열 데이터를 URL에 전달하기 위한 Base64 인코딩/디코딩 유틸 추가
  package-lock.json
  package.json
  src/util/arrayEncoding.test.ts
  src/util/arrayEncoding.ts
Labels: feat

#249 [FIX] 사용자 지정 토론 생성 시 팀 이름 관련 문제 수정
  src/page/TableComposition/hook/useTableFrom.tsx
Labels: fix

#262 [FIX] 31초 -> 30초가 되는 순간에만 타종하도록 로직을 변경
  src/mocks/handlers/customize.ts
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
Labels: fix

#261 [FEAT] URL 공유 기능 구현
  package-lock.json
  package.json
  src/components/LoadingSpinner.tsx
  src/components/ShareModal/ShareModal.stories.tsx
  src/components/ShareModal/ShareModal.tsx
  src/hooks/useTableShare.tsx
  src/page/TableListPage/components/Table.tsx
  src/page/TableOverviewPage/TableOverview.tsx
Labels: feat, chore, design

#264 [DEPLOY] main으로 배포 진행
  package-lock.json
  package.json
  src/components/LoadingSpinner.tsx
  src/components/ShareModal/ShareModal.stories.tsx
  src/components/ShareModal/ShareModal.tsx
  src/hooks/useTableShare.tsx
  src/mocks/handlers/customize.ts
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
  src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx
  src/page/CustomizeTimerPage/hooks/useCustomTimer.ts
  src/page/CustomizeTimerPage/hooks/useNormalTimer.ts
  src/page/TableComposition/hook/useTableFrom.tsx
  src/page/TableListPage/components/Table.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/util/arrayEncoding.test.ts
  src/util/arrayEncoding.ts
Labels: deploy

#266 [DESIGN] 타이머 반응형 구현
  .storybook/preview.tsx
  src/components/RoundControlButton/RoundControlButton.tsx
  src/page/CustomizeTimerPage/CustomizeTimerPage.tsx
  src/page/CustomizeTimerPage/NormalTimerTestPage.stories.tsx
  src/page/CustomizeTimerPage/NormalTimerTestPage.tsx
  src/page/CustomizeTimerPage/components/AdditionalTimerControlButton.tsx
  src/page/CustomizeTimerPage/components/AdditionalTimerController.tsx
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
  src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx
  src/page/CustomizeTimerPage/components/TimerController.tsx
  tailwind.config.js
Labels: design

#270 [FIX] 반응형 타이머 깨진 UI 수정
  src/page/CustomizeTimerPage/components/NormalTimer.tsx
  src/page/CustomizeTimerPage/components/TimeBasedTimer.tsx
Labels: fix, design

#272 [FIX] 작은화면 작전시간 타이머 깨짐 해결
  src/page/TimerPage/components/AdditionalTimerControlButton.tsx
  src/page/TimerPage/components/AdditionalTimerController.tsx
  src/page/TimerPage/stories/NormalTimerTestPage.stories.tsx
Labels: fix

#273 [FEAT] 회원/비회원 통합 유저플로우를 위한 데이터 패칭 훅 개선
  src/apis/apis/debateTable.ts
  src/apis/requests/debateTable.ts
  src/apis/responses/customize.ts
  src/apis/responses/debateTable.ts
  src/hooks/mutations/useAddDebateTable.ts
  src/hooks/mutations/useDeleteDebateTable.ts
  src/hooks/mutations/usePatchDebateTable.ts
  src/hooks/mutations/usePutDebateTable.ts
  src/hooks/query/useGetDebateTableData.ts
  src/mocks/handlers/customize.ts
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/hook/useTableFrom.tsx
  src/repositories/ApiDebateTableRepository.ts
  src/repositories/DebateTableRepository.ts
  src/repositories/SessionDebateTableRepository.ts
  src/type/type.ts
  src/util/sessionStorage.ts
Labels: feat, refactor

#278 [CHORE] 버그 및 잡무 처리
  index.html
  src/assets/keyboard/keyboard_key_A.png
  src/assets/keyboard/keyboard_key_l.png
  src/assets/timer/normal_timer.png
  src/assets/timer/timebased_perSpeaking_timer.png
  src/assets/timer/timebased_timer.png
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TimerPage/components/TimeBasedTimer.tsx
Labels: chore, fix
