Repository debate-timer/debate-timer-fe, pull requests merged in 2025-03, with the labels that each got.

#158 [CHORE] Issue 관련 스크립트 수정
  .github/workflows/Auto_Issue_Setting.yml
  .github/workflows/Issue_Noti.yml
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
Labels: chore

#159 [DESIGN] 타이머 페이지 수정
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/TimeTableItem.tsx
Labels: refactor, design

#152 [DESIGN] 시간표 설정 화면, 타임 박스 모달 피드백 사항 반영
  src/components/ErrorBoundary/ErrorPage.tsx
  src/components/ErrorBoundary/NotFoundPage.tsx
  src/components/ProsAndConsTitle/PropsAndConsTitle.tsx
  src/layout/components/footer/StickyFooterWrapper.tsx
  src/page/LoginPage/components/LinkButton/LinkButton.tsx
  src/page/TableComposition/TableComposition.test.tsx
  src/page/TableComposition/components/DebatePanel/DebatePanel.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableComposition/components/TimerCreationButton/TimerCreationButton.tsx
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
  src/page/TableListPage/components/Table/AddTable.tsx
  src/page/TableOverviewPage/TableOverview.tsx
Labels: design

#161 [DESIGN] 테마 색상 변경
  src/index.css
  src/layout/components/header/StickyTriSectionHeader.tsx
  tailwind.config.js
Labels: design

#163 [CHORE] notify-discord-comment yml 수정
  .github/workflows/PR_Comment_Noti.yml
Labels: chore

#165 [CHORE] 새로운 FE 멤버 영입으로 인한 Auto_PR_Setting 수정
  .github/workflows/Auto_PR_Setting.yml
Labels: chore

#167 [FIX] 이전 시간표에 따라 시간표 생성 모달 기본 입장이 변경되지 않는 문제 수정
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
Labels: fix

#168 [DESIGN] `useModal` 일부 변경
  src/hooks/useModal.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
Labels: design

#171 [DESIGN] 토론 테이블에 주제 표시, 주제 긴 경우 툴팁 추가
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/Table/Table.stories.tsx
  src/page/TableListPage/components/Table/Table.tsx
  src/type/type.ts
Labels: design

#175 [DESIGN] 시간표 아이템 개수 5개로 고정되도록 변경
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/TimeTableItem.tsx
  src/page/TimerPage/stories/TimeTable.stories.tsx
Labels: design

#180 [FIX] 작전시간 선택 후, 다임 시간표생성에서 작전시간이 유지되는 문제 수정
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
Labels: fix

#182 [FIX] 에러페이지에서 홈으로 가기 버튼이 동작하지 않는 문제 수정
  src/components/ErrorBoundary/ErrorBoundary.tsx
  src/components/ErrorBoundary/ErrorPage.tsx
Labels: fix

#174 [FIX] Discord 스크립트 오류 수정
  .github/workflows/Issue_Noti.yml
  .github/workflows/PR_Comment_Noti.yml
Labels: fix

#186 [FIX] 초기 speakerNumber를 상황에 맞게 초기화
  src/page/TableComposition/components/TimerCreationContent/TimerCreationContent.tsx
Labels: fix

#196 [FIX] 타이머 버그 해결
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/TimeTableItem.tsx
  src/page/TimerPage/components/Timer.tsx
  src/page/TimerPage/stories/TimeTableItem.stories.tsx
Labels: fix

#176 [REFACTOR] 대화 상자형 모달 별도 컴포넌트로 분리
  src/components/DialogModal/DialogModal.stories.tsx
  src/components/DialogModal/DialogModal.test.tsx
  src/components/DialogModal/DialogModal.tsx
  src/page/TableComposition/components/EditDeleteButtons/EditDeleteButtons.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
Labels: refactor

#205 [FIX] Discord 알림 스크립트 오류 수정
  .github/workflows/Issue_Noti.yml
  .github/workflows/PR_Comment_Noti.yml
Labels: fix

#201 [CHORE] 스타일 가이드 변경
  src/components/DialogModal/DialogModal.tsx
  tailwind.config.js
Labels: chore

#200 [DESIGN] 작전 시간 타이머 추가에 따른 공통 컴포넌트 분리
  src/components/RoundControlButton/RoundControlButton.stories.tsx
  src/components/RoundControlButton/RoundControlButton.tsx
  src/index.css
  src/page/TableComposition/components/TableNameAndType/TableNameAndType.tsx
  src/page/TableComposition/components/TimeBoxStep/TimeBoxStep.tsx
  src/page/TableOverviewPage/TableOverview.tsx
  src/page/TimerPage/components/TimeTable.tsx
Labels: refactor, design

#210 [FEAT] parliamentary/debate api 토론하기 버튼 재연결
  src/apis/apis/parliamentary.ts
  src/apis/responses/parliamentary.ts
  src/hooks/mutations/usePatchParliamentaryDebateTable.ts
  src/page/TableOverviewPage/TableOverview.tsx
Labels: feat

#211 [DESIGN] 테이블 목록 화면 디자인 개선
  src/page/TableListPage/TableListPage.test.tsx
  src/page/TableListPage/TableListPage.tsx
  src/page/TableListPage/components/Modal/CreateTableButton.tsx
  src/page/TableListPage/components/Modal/CreateTableModal.tsx
  src/page/TableListPage/components/Modal/DeleteModalButton.tsx
  src/page/TableListPage/components/Modal/DropdownForDebateType.tsx
  src/page/TableListPage/components/Modal/EditButton.tsx
  src/page/TableListPage/components/Modal/EditTableButton.tsx
  src/page/TableListPage/components/Modal/EditTableModal.tsx
  src/page/TableListPage/components/Table.tsx
  src/page/TableListPage/components/Table/AddTable.stories.tsx
  src/page/TableListPage/components/Table/AddTable.tsx
  src/page/TableListPage/components/Table/Table.stories.tsx
  src/page/TableListPage/components/Table/Table.tsx
  src/page/TableListPage/stories/Table.stories.tsx
Labels: test, design

#209 [DESIGN] 일반 타이머 개선
  src/page/TimerPage/TimerPage.test.tsx
  src/page/TimerPage/TimerPage.tsx
  src/page/TimerPage/components/TimeTable.tsx
  src/page/TimerPage/components/Timer.tsx
  src/page/TimerPage/stories/Timer.stories.tsx
  tailwind.config.js
Labels: test, design

#214 [DESIGN] `DialogModal` 버튼 호버 색상 추가
  src/components/DialogModal/DialogModal.tsx
Labels: design
